name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod


      - name: Check Go version
        id: check-go-version
        run: |
          echo "GO_VERSION=$(go version | awk '{print $3}')" >> $GITHUB_ENV

      - name: check go cache
        id: check-go-cache
        uses: actions/cache@v4
        with: 
          lookup-only: true
          enableCrossOsArchive: true
          path: |
            ~/go/pkg/mod
            ~.cache/go-build
          key: setup-go-${{ runner.os }}-${{ runner.arch }}-go-${{ steps.check-go-version.outputs }}-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-


      - name: Install dependencies
        if: steps.check-go-cache.outputs.cache-hit != 'true'
        run: |
          go mod download

      - name: Run tests
        run: |
          go test -v ./...